### ISSUE TITLE
Patient_id in prescription becomes <<"undefined">> when it is added to a patient object

### ISSUE THREAD

**Issue by Maryam81609** [goncalotomas/FMKe#101]
Database: Antidote
Sequence of fmk API calls (on a single node):
1- create patient1
2- create pharmacy1
3- create staff1
4- create prescription1 for objects in 1,2,3

Then patient_id in the prescription field in patient1 is `<<"undefined">>`.

Here is the created prescription:
```Erlang
Presc: {prescription,<<"1">>,<<"1">>,<<"1">>,<<"1">>,<<"06-17-17">>,
                     <<"undefined">>,
                     [<<"drugs">>],
                     <<"prescription_not_processed">>}
```
And here is the list of prescriptions I fetched from patient1:
```Erlang
Patient1 prescs: [{prescription,<<"1">>,<<"undefined">>,<<"1">>,<<"1">>,
                                <<"06-17-17">>,<<"undefined">>,
                                [<<"drugs">>],
                                <<"prescription_not_processed">>}]
```

**Comment by goncalotomas** [comment]
Hi Maryam,

This is "on purpose". At the moment, FMKe is using a single record to store patient information, and that record has the following fields:

- id
- patient_id
- pharmacy_id
- prescriber_id
- is_processed
- drugs
- date_prescribed
- date_processed

The prescription object itself will have all of this fields filled in, and will be correctly stored in the data store.
However, it is easy to understand that the prescriptions inside the patients don't really need to have information about the patient object, since you will have already information in the patient record itself. For this reason, `patient_id` is not filled in when creating the patient prescriptions, `pharmacy_id` is not filled when creating the prescriptions inside the pharmacies, and `prescriber_id` is also not filled inside the prescriptions for the doctors. :)

However, when you fetch the patient prescriptions I'm using the same Erlang record, and of course, those fields are appearing as "undefined". For the moment this is expected behaviour, but I thought of a way to make this invisible to the user.

I will see if the approach I'm thinking about works, and if it does I will fix this soon :)

**Comment by goncalotomas** [comment]
This was actually a very cool feature to have added, since testing the HTTP API I have realised that the following is possible:

```erlang
Prescription = fetch("http://localhost:9090/prescriptions/123"),
Patient = fetch("http://localhost:9090/patients/1"),
Pharmacy = fetch("http://localhost:9090/pharmacies/1"),
Staff = fetch("http://localhost:9090/staff/1"),
%% Patern match the Prescription object against all others!
[Prescription] = proplists:get_value(<<"patientPrescriptions">>,Patient),
[Prescription] = proplists:get_value(<<"pharmacyPrescriptions">>,Pharmacy),
[Prescription] = proplists:get_value(<<"staffPrescriptions">>,Staff),
```

So basically leverage pattern matching to make sure that every prescription is the same, comparing the top level one with others nested inside other entities. Only really possible after this change :)

Thanks again Maryam for reporting this!
