### ISSUE TITLE
Instructions for running the benchmark in multiple databases

### ISSUE THREAD

**Issue by yunhaom94** [goncalotomas/FMKe#201]
Hello, 

Sorry if this sounds trivial. I'm new to erlang and trying to compare perfomance of my Redis(geo-replicatied CRDB) set-up and AntidoteDB set-up. 
I read the documention and don't understand how should I run it, I tried to `make bench-redis` but turns out travis.sh is missing and I don't know how to connect to my running Redis server.

Thank you.

**Comment by goncalotomas** [comment]
Hi!

You're completely right. I checked and there were some changes that have broken the previous `bench-redis` Makefile target, and this makes some of the existing documentation outdated. I'll try to see if I can help you benchmark both systems while I fix the issue.

I see that you've forked Redis, and I would like to know if your Redis database is compatible with the Redis Cluster protocol. If so, then we can use the existing drivers for it.

Here are some instructions to run the FMKe benchmark.

Software you will need:
- [Erlang 21](http://erlang.org/downloads)
- [rebar3](http://www.rebar3.org)
- R (programming language, for generating pretty graphs in the end)
- FMKe application server (this repository)
- [fmke_populator](https://github.com/goncalotomas/fmke_populator)
- [fmke_client](https://github.com/goncalotomas/fmke_client)

To compare the results of multiple databases you can follow these steps:
1. Launch your Redis instances and set them up as a cluster
1. [FMKe application server]: configure `config/fmke.config` too look something like [this](https://gist.github.com/goncalotomas/2460a6f44d43b1918662bf9dd8f5a015), changing the port numbers according to your deployment
1. [FMKe application server]: Run `rebar3 shell` on a terminal, this will run the FMKe application server
1. Compile [fmke_populator](https://github.com/goncalotomas/fmke_populator), it will serve to populate the database through the FMKe server before the benchmark.
1. [fmke_populator]: Run `./_build/default/bin/fmke_populator fmke@127.0.0.1`. It might take a few minutes but it will populate your Redis cluster through the already running FMKe application server.
1. Compile [fmke_client](https://github.com/goncalotomas/fmke_client). This is the part of the benchmark that will now generate load and measure the performance of the database. If you are running the setup in localhost with the fmke.config file I provided, you don't need to change the configuration.
1. [fmke_client]: Run `./_build/default/bin/lasp_bench fmke_client.config`. This will start the benchmark and will keep going for 20 minutes (configurable in `config/fmke_client.config`). After it is done, you can use `make results` and that will run an R script that will generate graphs from the benchmark that you just run. Give this file an appropriate name so that you don't forget which configuration was used to generate those results.
1. [fmke_client]: Repeat the above steps for any supported database that you want to compare your version of Redis with (or even a vanilla version of Redis Cluster!).

Once you're able to do these tests, you can distribute the components through different machines and the only thing you'll need to change are some configuration files.

Please let me know if you have any issues going through these steps!

**Comment by goncalotomas** [comment]
Hmm, this seems to be a problem with the `eredis_cluster` library, which apparently is not being able to connect to your cluster. Do you know how to use the Redis Cluster version instead of the Redis Enterprise CRDB?

If you are able to use it with Redis Cluster but not with the Enterprise version, then it means that either the communication protocol is different, or that some unexpected error is not allowing `eredis_cluster` to start. Would it be OK to ask you to try configuring a Redis Cluster and trying FMKe with that? We've been running several tests with it and we have not had issues.
I ask this because I assume since it is an enterprise version that I might need some sort of license to use it. If that's not the case and you can link me some documentation I'd be happy to try it out myself.

Thanks for sticking with me.

**Comment by yunhaom94** [comment]
So I tried using Redis version 4.0.10 and set-up another cluster, FMKe application server seemed to be able to connect(No more errors after `===> Booted fmke`), however step 5 failed again with another connection error.
```
$./_build/default/bin/fmke_populator fmke@127.0.0.1
Using opts=[{cookie,fmke},
            {dataset,"standard"},
            {force,false},
            {nodename,'fmke_populator@127.0.0.1'},
            {procs,100},
            {queue,100},
            {retries,3},
            {timeout,10},
            {update,10},
            {skip_prescriptions,false},
            {only_prescriptions,false}]
=INFO REPORT==== 15-Oct-2018::22:39:37.366588 ===
Protocol 'inet_tcp': register/listen error: econnrefused

=SUPERVISOR REPORT==== 15-Oct-2018::22:39:37.366775 ===
    supervisor: {local,net_sup}
    errorContext: start_error
    reason: {'EXIT',nodistribution}
    offender: [{pid,undefined},
               {id,net_kernel},
               {mfargs,{net_kernel,start_link,
                                   [['fmke_populator@127.0.0.1',longnames],
                                    false]}},
               {restart_type,permanent},
               {shutdown,2000},
               {child_type,worker}]
Error: unable to start distributed erlang node: {{shutdown,
                                                  {failed_to_start_child,
                                                   net_kernel,
                                                   {'EXIT',nodistribution}}},
                                                 {child,undefined,
                                                  net_sup_dynamic,
                                                  {erl_distribution,
                                                   start_link,
                                                   [['fmke_populator@127.0.0.1',
                                                     longnames],
                                                    false]},
                                                  permanent,1000,supervisor,
                                                  [erl_distribution]}}

```

Here is the fmke.config


```
{database_addresses, ["172.17.0.2"]}.
{database_ports, [15399]}.
{target_database, redis}.
{optimized_driver, true}.
{data_model, non_nested}.
{connection_pool_size, 1}.
{http_port, 9090}.
```


As for CRDB, it's from RedisLab's Redis Enterpise, which is basically another layer on top of Redis cluster that connect many clusters and replicate the dabase between them for geo-replication. There is a trial version which I am using, and I followed these two instructions: 
https://redislabs.com/redis-enterprise-documentation/getting-started/docker/linux/ 
https://redislabs.com/redis-enterprise-documentation/administering/database-operations/create-crdb/
and setting up 2 clusters running in docker for testing. I ran YCSB before on it and it was successful. 

Thanks a lot for your help, I greatly appreciate it since you have the only Benchmark that supports the databases I need to test.

**Comment by goncalotomas** [comment]
There are some clues as to what is happening on the traces you've provided.
Since we last spoke I was told by a Redis Labs employee that the protocols that Redis Cluster and Redis Enterprise CRDB speak are supposed to be compatible. So we can rule out issues in the client library (for now).

One thing we can do to check connectivity between FMKe and Redis is to execute some command once FMKe boots up (press ENTER once you see the "Booted fmke" message to see the shell prompt:
```erl-sh
===> Booted fmke
1> fmke:get_patient_by_id(1).
{error,not_found}
2> fmke:create_patient(1, "Jerry Smith", "Vancouver, BC").
ok
3> fmke:get_patient_by_id(1).
{patient,1,"Jerry Smith","Vancouver, BC",[]}
```
This will serve as a definite test that you can now speak to Redis Enterprise CRDB successfully.

With regards to the error that you're seeing, it seems to be more easily fixed. You see, Erlang nodes are able to connect to other nodes via a distributed communication layer, which is provided by [epmd](http://erlang.org/doc/man/epmd.html). What seems to be happening is that fmke_populator is trying to communicate with the application server and is failing because the distribution layer is not running. This typically manifests itself with the `reason: {'EXIT',nodistribution}` that I see in the error trace you provided.

To fix the issue, running `epmd -daemon` before starting both components should be enough. This way, both components will be able to find and communicate with each other.

I am updating the Wiki pages with information relative to the difficulties you're facing, since others are likely to bump into them as well. Thanks for sticking with me so far :)

**Comment by yunhaom94** [comment]
fmke_populator gives me this error now
'''
Booted distributed erlang node 'fmke_populator@127.0.0.1', using cookie fmke
Error: could not ping FMKe node: 'fmke@127.0.0.1'
'''

Sorry for the late reply, having a busy week, I will try the CRDB test later and update.

**Comment by yunhaom94** [comment]
Yes both were correct.

**Comment by yunhaom94** [comment]
It shows `1>`
![image](https://user-images.githubusercontent.com/14297873/47189764-280fea00-d30c-11e8-8bf1-83f7ac5ed6ba.png)

**Comment by goncalotomas** [comment]
Argh, this one is totally my fault, sorry! That was not supposed to happen. I had thought I had there was a default nodename fmke@127.0.0.1` but apparently it is not set. To confirm this you can run `node().` on that same shell and you will likely see `nonode@nohost`.

This means that your `rebar3 shell` command that you run in step 3 should be replaced by `rebar3 shell --name fmke@127.0.0.1`. That way, the FMKe application will start a distributed Erlang node with the specified name, which is exactly what the populator is looking for.

I'm going to edit the instructions to reflect this change.

**Comment by yunhaom94** [comment]
I was able to connect FMKe server to Redis Cluster now (I tried the commands from https://github.com/goncalotomas/FMKe/issues/201#issuecomment-430209913 in shell, they worked), however the populator still won't connect to FMKe node because it is refused somehow.
![1](https://user-images.githubusercontent.com/14297873/47250509-36cfcd00-d3f0-11e8-9186-ccab72e232ed.jpg)


I am still not be able to run FMKe with Redis Enterprise version, FMKe exit with same error message. None of the commands work neither.

**Comment by goncalotomas** [comment]
On one hand, great. The existing driver seems to work with Redis Enterprise. Now to fix the link between the application server and the populator.

The `fmke_populator` is not being able to connect to the application server because despite being able to reach it, it does not have a properly configured cookie (read [this](http://erlang.org/doc/reference_manual/distributed.html) for more info). I have several instances where I am setting this value, but `rebar3` shell is apparently not reading this configuration.
I have written a patch that is pending CI tests that will fix this issue by adding specific defaults to both the nodename (previously `nonode@nohost`) and cookie (previously unset). GitHub seems to be going some issues, but once this PR is tested I will report back once done.

**Comment by yunhaom94** [comment]
> On one hand, great. The existing driver seems to work with Redis Enterprise. Now to fix the link between the application server and the populator.

Sorry I should mention that Redis Cluster is not with Enterprise instead the open-source version! I am testing both versions at the same time to figure out how FMKe works and how to make it work with Redis Enterprise CRDB. So I was running same steps on both in my reports.

**Comment by goncalotomas** [comment]
No problem, as I got [informal confirmation](https://stackoverflow.com/questions/34153154/whats-the-difference-between-open-source-redis-cluster-and-redis-labs-enterpris/34156821?noredirect=1#comment92553995_34156821) from the Chief Developers Advocate at Redis Labs that the protocols are basically the same, so we should not have any issues with the existing driver.

As for the other changes that were pending, GitHub appears to be stabilised to I merged the changes over to master. When possible you can pull the latest changes from master and try again using only `rebar3 shell` in step 3.
Again, I'll update the instructions above to reflect the recent changes.

Thanks!

**Comment by yunhaom94** [comment]
I tried `rebar3 shell` and it was able started FMKe node correctly, the poplulator was able to connect but crashed immdetaly after
![1](https://user-images.githubusercontent.com/14297873/47366148-0d8e9580-d6ab-11e8-800b-0c754c036a24.jpg)

**Comment by goncalotomas** [comment]
I think I might have an idea why this is failing. Are you running the script on a clean cluster?
Does the database contain data (e.g. data inserted through the shell of the application server)?

If you think there might be data already present in the database, you need to use the force flag (`-f` or `--flag`):

```shell
./_build/default/bin/fmke_populator --force fmke@127.0.0.1
```

This will skip any errors in case the insertion procedure reports an existing record.
I will work on a PR in order to add a more understandable error message. Sorry this process has been plagued with errors..

**Comment by yunhaom94** [comment]
Ah, there was something in the database, I shall try it now with clean database.

**Comment by yunhaom94** [comment]
Ahh, that's good, I'll try it again and report back later! I used the `fmke_client.config` from `./expamles/fmke_client.config`

```
% Run at max, i.e.: as quickly as possible
{mode, max}.

%% test duration
{duration, 20}.

% Run 16 concurrent clients
{concurrent, 16}.

%% The module name of the driver that Basho Bench will use to generate load.
{driver, lasp_bench_driver_fmke_client}.

%% necessary code to run the client
{code_paths,
  [
    "_build/default/lib/lager",
    "_build/default/lib/unicode_util_compat",
    "_build/default/lib/jsx",
    "_build/default/lib/lasp_bench",
    "_build/default/lib/hackney",
    "_build/default/lib/idna",
    "_build/default/lib/mimerl",
    "_build/default/lib/metrics",
    "_build/default/lib/certifi",
    "_build/default/lib/ssl_verify_fun"
  ]
}.

%%
{key_generator, {int_to_bin_bigendian, {uniform_int, 5000000}}}.

%%
{value_generator, {fixed_bin, 10000}}.

%% Configuration settings for FMK servers.
%% List of server IPs
{fmk_server_ips, ["127.0.0.1"]}.
%% List of HTTP ports to connect (1-to-1 correspondence to above list)
{fmk_server_ports, [9090]}.

{numpatients,1000000}.
{numfacilities,50}.
{numpharmacies,300}.
{numstaff,10000}.
{numprescriptions,5000}.
{zipf_size,5000}.
{zipf_skew,1}.

{operations,[
  {get_pharmacy_prescriptions, 27},
  {get_prescription_medication, 27},
  {get_staff_prescriptions, 14},
  {create_prescription, 8},
  {get_processed_prescriptions, 7},
  {get_patient, 5},
  {update_prescription, 4},
  {update_prescription_medication, 4},
  {get_prescription, 4}
]}.
```

**Comment by goncalotomas** [comment]
That is the correct file. You should be able to get some results with that :smile:

**Comment by yunhaom94** [comment]
Thanks a lot for the help!I generated the graph, this looks like what it should look like right?
![1](https://user-images.githubusercontent.com/14297873/47444532-a80ed780-d784-11e8-8c62-a4ce86000a7d.jpg)

I need to try this with AntidoteDB and Riak, I'll let you know if anything wrong. Also Redis Enterprise still doesn't seem to work.

**Comment by goncalotomas** [comment]
Hey!

Yes, that looks about right. Out of curiosity, what sized cluster did you use, and did you use the durability option?
What errors are you getting on Redis Enterprise?

**Comment by yunhaom94** [comment]
I am running on a 3 masters+3 slaves cluster with durability created by default `create-cluster` script in `/utils/create-cluster/` of Redis.

For Redis Enterpise, is the same error I posted https://github.com/goncalotomas/FMKe/issues/201#issuecomment-429595398 here.

**Comment by goncalotomas** [comment]
OK, so I'm going to take a look into it, get a testing license for Redis Enterprise and see what I can do to fix those errors. Thanks for sticking with me.

**Comment by yunhaom94** [comment]
Thanks! Although I am running on the trial version of Redis Enterprise, I am not sure if that will affact anything.

**Comment by yunhaom94** [comment]
Hi, is there any update on the issues I posted?

**Comment by goncalotomas** [comment]
Not yet. I'll provide an update before the week is out.

**Comment by goncalotomas** [comment]
Can you describe the exact steps you used to create the Redis CRDB database?
I'm following the instructions [from here](https://docs.redislabs.com/latest/rs/getting-started/creating-database/crdbs/#test-connectivity) and I am not being able to connect 2 clusters together via the web interface as described (tried in Safari, Firefox and Chrome).

**Comment by yunhaom94** [comment]
That was the insturctions I followed. Make sure the addresses, ports, username and password are correct and all the fields are filled like it's showed on picture. What kind of error are you getting?

**Comment by goncalotomas** [comment]
Either a 400 Bad Request or a 401 Unauthorised in the last step of the connecting clusters step, when I click`Activate` in the form. I'm copy pasting the database and cluster names off of the guide and I've tried many times in different browsers.

**Comment by goncalotomas** [comment]
using the following commands to start the nodes:
```sh
docker run -d --cap-add sys_resource -h rp1_node1 --name rp1_node1 -p 8443:8443 -p 9443:9443 -p 12000:12000 redislabs/redis
docker run -d --cap-add sys_resource -h rp2_node1 --name rp2_node1 -p 8445:8443 -p 9445:9443 -p 12002:12000 redislabs/redis
```

I'm noticing that once I set the admin details, I get logged out frequently. Is that normal?

**Comment by yunhaom94** [comment]
Ah I think you should login to the server one at the time or use incognito mode for one of the server. I noticed that opening multiple broswer windows connecting to different server causing weired issues with the inferface.

**Comment by goncalotomas** [comment]
Ok, thanks, going to try that and I'll get back to you soon

**Comment by goncalotomas** [comment]
Got past that point, but now clicking in `Activate` gives me a "Cluster memory is fully allocated" error. Have you seen this before?

**Comment by yunhaom94** [comment]
I don't think I've seen that, have you changed the memory limit above it?

**Comment by goncalotomas** [comment]
I did. By default it was 0.1 GiB, I set it to 4 GiB

**Comment by goncalotomas** [comment]
Regardless of what I put there, I get the same result, despite having enough free memory:
https://imgur.com/4UqqKH5
https://imgur.com/3vTa7O4
Googling for the error didn't help much either I'm afraid...

**Comment by goncalotomas** [comment]
Just to be sure I'm not being silly, can you show me the form data that you're submitting? Do you have to add `cluster1.local` and `cluster2.local` in /etc/hosts or something?
Other than that, the credentials that you put in the interface don't have to be real right? I've tried multiple combinations with no luck so far :(

**Comment by yunhaom94** [comment]
![image](https://user-images.githubusercontent.com/14297873/48679634-bcb27580-eb60-11e8-9b4d-b07c984bc57f.png)
I just tried it and this worked you don't need special hosts for running locally, I am not sure why are you seeing that error... maybe is a mac problem?

**Comment by goncalotomas** [comment]
I will create a VM with Ubuntu first thing tomorrow morning and I'll check back. Once you got past this point, what were you configuring in `fmke.config`? Which port did you select? The endpoint port?

**Comment by yunhaom94** [comment]
That is correct.

**Comment by yunhaom94** [comment]
I saw you pull request and will try it out once it's working. Thank you for the update, I appriated the work you have done, it's really helpful for me.

**Comment by goncalotomas** [comment]
Don't forget, the changes you want are in the `driver/redis-crdb` branch! (for now)
I am going to test it now and if it works I'll merge it to master.

**Comment by goncalotomas** [comment]
This is an error compiling the Cassandra library.
I'm assuming, for the compiling step to fail, that you don't have the Cassandra dependencies. Please follow the steps listed [here](https://github.com/silviucpp/erlcass/wiki/Getting-started#ubuntu) and try again to see if you still get the error. I'm assuming you are using 18.04.

**Comment by goncalotomas** [comment]
I think you might have missed `cmake`, at least from looking at the error traced:
```
./build_deps.sh: line 93: cmake: command not found
```

**Comment by yunhaom94** [comment]
Opps, sorry I just noticed that there the errors are new after installing the dependencis

```
===> Compiling antidote_pb_codec
===> Compiling antidotec_pb
===> Compiling erlcass
cpp-driver fork already exist. delete _build/deps for a fresh checkout.
make[1]: Entering directory '/home/redis1/FMKe/_build/default/lib/erlcass/c_src'
 CPP    uuid_serialization.cc
 CPP    cass_binding.cc
 CPP    nif_cass_statement.cc
In file included from /home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/address.hpp:22:0,
                 from /home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/serialization.hpp:20,
                 from /home/redis1/FMKe/_build/default/lib/erlcass/c_src/uuid_serialization.cc:2:
/home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/third_party/sparsehash/src/sparsehash/dense_hash_set:103:10: fatal error: sparsehash/internal/sparseconfig.h: No such file or directory
 #include <sparsehash/internal/sparseconfig.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
nif.mk:78: recipe for target '/home/redis1/FMKe/_build/default/lib/erlcass/c_src/uuid_serialization.o' failed
make[1]: *** [/home/redis1/FMKe/_build/default/lib/erlcass/c_src/uuid_serialization.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/ref_counted.hpp:20:0,
                 from /home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/buffer.hpp:20,
                 from /home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/abstract_data.hpp:20,
                 from /home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/statement.hpp:20,
                 from /home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/execute_request.hpp:23,
                 from /home/redis1/FMKe/_build/default/lib/erlcass/c_src/nif_cass_statement.cc:3:
/home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/atomic.hpp:20:10: fatal error: cassconfig.hpp: No such file or directory
 #include "cassconfig.hpp"
          ^~~~~~~~~~~~~~~~
compilation terminated.
nif.mk:78: recipe for target '/home/redis1/FMKe/_build/default/lib/erlcass/c_src/nif_cass_statement.o' failed
make[1]: *** [/home/redis1/FMKe/_build/default/lib/erlcass/c_src/nif_cass_statement.o] Error 1
In file included from /home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/ref_counted.hpp:20:0,
                 from /home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/data_type.hpp:24,
                 from /home/redis1/FMKe/_build/default/lib/erlcass/c_src/cass_binding.cc:7:
/home/redis1/FMKe/_build/default/lib/erlcass/_build/deps/cpp-driver/src/atomic.hpp:20:10: fatal error: cassconfig.hpp: No such file or directory
 #include "cassconfig.hpp"
          ^~~~~~~~~~~~~~~~
compilation terminated.
nif.mk:78: recipe for target '/home/redis1/FMKe/_build/default/lib/erlcass/c_src/cass_binding.o' failed
make[1]: *** [/home/redis1/FMKe/_build/default/lib/erlcass/c_src/cass_binding.o] Error 1
make[1]: Leaving directory '/home/redis1/FMKe/_build/default/lib/erlcass/c_src'
Makefile:12: recipe for target 'nif_compile' failed
make: *** [nif_compile] Error 2
===> Hook for compile failed!
```

**Comment by goncalotomas** [comment]
OK, the next clue is in the following trace line:
```
/usr/bin/ld: cannot find -lcassandra_static
```
This typically happens when you are installing an old version of libuv (there is v0 and v1). You need to ensure that when installing `libuv-dev` that you get v1. Try using the following command to fetch this specific Cassandra dependency:
```
sudo apt install libuv1-dev
```
While you are getting errors on the Cassandra compilation, you should delete `_build` between attempts :)

**Comment by yunhaom94** [comment]
I deleted the old libuv-dev and downloaed manually and worked! 

However the fmke_populator stopped working again

```
./_build/default/bin/fmke_populator fmke@127.0.0.1.
Using opts=[{cookie,fmke},
            {dataset,"standard"},
            {force,false},
            {nodename,'fmke_populator@127.0.0.1'},
            {procs,100},
            {queue,100},
            {retries,3},
            {timeout,10},
            {update,10},
            {skip_prescriptions,false},
            {only_prescriptions,false}]
Booted distributed erlang node 'fmke_populator@127.0.0.1', using cookie fmke
Error: could not ping FMKe node: 'fmke@127.0.0.1.'

```

**Comment by yunhaom94** [comment]
I got it working by deleting the old libuv-dev and downloading a new version manually!

However the fmke_poplutor stoped working again:

```
Booted distributed erlang node 'fmke_populator@127.0.0.1', using cookie fmke
Error: could not ping FMKe node: 'fmke@127.0.0.1.'
 ```

and this after I restarting a couple of times

```
Booted distributed erlang node 'fmke_populator@127.0.0.1', using cookie fmke
escript: exception error: no match of right hand side value undefined
  in function  fmke_populator:main/1 (/home/redis1/fmke_populator/_build/default/lib/fmke_populator/src/fmke_populator.erl, line 52)
  in call from escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 

```

**Comment by goncalotomas** [comment]
You're trying to reach `fmke@127.0.0.1.` (extra dot at the end) which is not a valid Erlang node name.
Run it like so, without the trailing dot:
```
./_build/default/bin/fmke_populator fmke@127.0.0.1
```

**Comment by yunhaom94** [comment]
I got the second error then with this command.

**Comment by goncalotomas** [comment]
Yes, that was due to the latest changes I made here, which on some configurations don't fill in the `target_database`. I patched `fmke_populator`, can you pull the latest changes and try again?

**Comment by yunhaom94** [comment]
It worked out well. Thanks!

**Comment by goncalotomas** [comment]
No problem.
In your setup have you figured out how to add multiple nodes to a single cluster in Redis CRDB?

**Comment by yunhaom94** [comment]
![1](https://user-images.githubusercontent.com/14297873/49164739-b14c1080-f2fd-11e8-8448-9116d9006b2c.jpg)

Just use Join Cluster option instead when first setting it up.
https://docs.redislabs.com/latest/rs/concepts/high-availability/clustering/
